# {{ ansible_managed }}

/proc/
/root/.bundle/cache/
/root/.cache/
/root/.gem/
/root/v22017115078354939_docker.qcow2
/srv/chroot/monitor/tmp/
/sys/
/tmp/
/var/backups/
/var/cache/
/var/lib/apt/lists/
/var/lib/changetrack/
/var/lib/icinga/spool/
/var/lib/munin/plugin-state/
/var/lib/munin/*.tmp*
/var/lib/nginx/proxy/
/var/lib/smartmontools/
/var/lib/spool/
/var/lib/php7/sess_
/var/lib/php7/sessions/
/var/log/
/var/run/
/var/spool/pnp4nagios/
/var/tmp/

# only daily backups
/var/lib/autopostgresqlbackup/weekly
/var/lib/autopostgresqlbackup/monthly